.\" This file is written in Manual Page Editor 0.4.1
.TH "gfxindex" "1" "1.3" "Fredrik Rambris" ""
.SH "NAME"
.LP 
gfxindex \- Thumbnailer and indexer
.SH "SYNTAX"
.LP 
gfxindex [\fIoption\fP] <title>

.SH "DESCRIPTION"
.LP 
GFXIndex is a tool to manage your picture collection by creating thumbnails
(small representation of the original picture) and HTML\-indexes. 

The thumbnails are by default put in the directory thumbnails and the
indexes in the same directory as the images. 
.SH "OPTIONS"
.LP 
.TP 
\fB\-q, \-\-quiet\fR
don't print any progress information.
.TP 
\fB\-d, \-\-dir\fR=<\fIdirectory\fP>
<\fIdirectory\fP> to start with
.TP 
\fB\-o, \-\-overwrite\fR
overwrite thumbnails
.TP 
\fB\-r, \-\-recursive\fR
traverse dirs
.TP 
\fB\-T, \-\-nothumbs\fR
don't make thumbnails
.TP 
\fB\-p, \-\-pad\fR
pad thumbnails for equal size
.TP 
\fB\-w, \-\-thumbwidth\fR=<\fIpixels\fR>
width of thumbnails
.TP 
\fB\-h, \-\-thumbheight\fR=<\fIpixels\fR>
height of thumbnails
.TP 
\fB\-Q, \-\-quality\fR=<\fInum\fR>
JPEG quality of thumbs. 0 crap, 100 good
.TP 
\fB\-c, \-\-thumbbgcolor\fR=<\fIcolorspec\fR>
backgroundcolor of thumbnails
.TP 
\fB\-b, \-\-thumbbevel\fR
beveled thumbnails
.TP 
\fB\-g, \-\-bevelbg\fR=<\fIcolorspec\fR>
backgroundcolor in beveled state
.TP 
\fB\-l, \-\-bevelbright\fR=<\fIcolorspec\fR>
color of bright edges in bevel
.TP 
\fB\-m, \-\-beveldark\fR=<\fIcolorspec\fR>
color of dark edges in bevel
.TP 
\fB\-f, \-\-scalefine\fR
use high quality (slower) rescaler
.TP 
\fB\-i, \-\-noindexes\fR
don't create HTML indexes
.TP 
\fB\-C, \-\-nocredits\fR
don't show credits
.TP 
\fB\-t, \-\-notitles\fR
don't show filenames
.TP 
\fB\-n, \-\-numlink\fR
use numeric links to individial pages
.TP 
\fB\-u, \-\-navthumbs\fR=<\fIpercent\fR>
use thumbnails for Prev and Next (set scale)
.TP 
\fB\-x, \-\-numx\fR=<\fInum\fR>
number of thumbnails per row
.TP 
\fB\-y, \-\-numy\fR=<\fInum\fR>
number of rows per page
.TP 
\fB\-a, \-\-bodyargs\fR=<\fIstring\fR>
statements inserted in the BODY tag
.TP 
\fB\-e, \-\-cellargs\fR=<\fIstring\fR>
statements inserted in the TD tag
.TP 
\fB\-s, \-\-css\fR=<\fIpath\fR>
relative path to Cascading StyleSheets
.TP 
\fB\-\-parentdoc\fR=<\fIpath\fR>
document linked to on Parent links
.TP 
Strings that make up the navbar
\fB\-\-left\fR=<\fIstring\fR>
.br 
\fB\-\-space\fR=<\fIstring\fR>
.br 
\fB\-\-divider\fR=<\fIstring\fR>
.br 
\fB\-\-right\fR=<\fIstring\fR>
.br 
\fB\-\-prev\fR=<\fIstring\fR>
.br 
\fB\-\-next\fR=<\fIstring\fR>
.br 
\fB\-\-index\fR=<\fIstring\fR>
.br 
\fB\-\-parent\fR=<\fIstring\fR>
.SH "FILES"
.LP 
\fI/usr/bin/gfxindex\fP 

.SH "AUTHORS"
.LP 
Fredrik Rambris <fredrik@rambris.com>
.SH "HOMEPAGE"
Up\-to\-date information about the program can be found at the official website
http://fredrik.rambris.com/gfxindex
